[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["cd server && npm ci"]

[phases.build]
cmds = ["echo 'No build step needed for server'"]

[start]
cmd = "cd server && npm start"